plugins:
  apt_crowd_api_enabled:
    default: false
    client: true
  apt_crowd_api_uri:
    default: ""
    client: true  
  apt_crowd_api_username:
    default: ""
    client: false
  apt_crowd_api_password:
    default: ""
    client: false
